# Generated by Django 3.1.2 on 2020-10-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('rank', models.CharField(max_length=15, verbose_name='Звание')),
                ('date_of_birth', models.DateTimeField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='PublicationsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Публикация')),
                ('source', models.CharField(max_length=50, verbose_name='Источник')),
                ('publicationType', models.CharField(max_length=20, verbose_name='Тип публикации')),
                ('number_of_pages', models.IntegerField(verbose_name='Число страниц')),
                ('authors', models.CharField(max_length=20, verbose_name='Авторы')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
